### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by Jean-PierreGassin** [jfalconer/counterwatch#5]
Hey @jfalconer, I'm really keen to use this project for some hero balancing comparisons, are you still maintaining it?

If not, I have a few friends @ @valvesoftware that would be willing to takeover.

Let me know your thoughts.

**Comment by joelfalconer** [comment]
Hey @Jean-PierreGassin I think it's best to let them keep their efforts concentrated on HL3

**Comment by Jean-PierreGassin** [comment]
Hey @joelfalconer just following up on this, I was recently contacted by @ValveSoftware in regards to this repository and they are willing to call Linus Tech Tips and have him take a glance.
